 
--drop table usuarios
CREATE TABLE usuarios(
consecutivo BIGINT IDENTITY(1,1) NOT NULL,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
run varchar(15) NOT NULL UNIQUE,
id_genero	tinyint NOT NULL,
fecha_nacimiento DATETIME NOT NULL,
telefono varchar(15),
email varchar(100) NOT NULL,
direccion varchar(100) NOT NULL,
direccion_detalle varchar(100),
id_comuna SMALLINT NOT NULL,
oficio varchar(50),
medio_enterar SMALLINT,
medicamentos_alergias varchar(200),
embarazo bit,
meses_embarazo tinyint,
observaciones_especiales varchar(max),
examen_visual bit,
password varchar(100),
pago_aprobado bit default 0,
acceso_habilitado bit default 0,
usuario_creacion varchar(50),
fecha_creacion DATETIME,
usuario_modificacion varchar(50),
fecha_modificacion DATETIME
);

GO

INSERT INTO usuarios (
    nombre,
    apellido,
    run,
    id_genero,
    fecha_nacimiento,
    telefono,
    email,
    direccion,
    direccion_detalle,
    id_comuna,
    oficio,
    medio_enterar,
    medicamentos_alergias,
    embarazo,
    meses_embarazo,
    observaciones_especiales,
    examen_visual,
    password,
    pago_aprobado,
    acceso_habilitado,
    usuario_creacion,
    fecha_creacion,
    usuario_modificacion,
    fecha_modificacion
)
VALUES (
    'Juan',
    'Pérez',
    '12345678-9',
    1,
    '1990-05-15',
    '3001234567',
    'juan.perez@example.com',
    'Calle Falsa 123',
    'Apto 4B',
    1,
    'Carpintero',
    1,
    'Ninguna',
    0,
    NULL,
    'Sin observaciones',
    1,
    '123',
    1,
    1,
    'admin',
    GETDATE(),
    NULL,
    NULL
);