<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>plataforma_ecp.api</RootNamespace>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.20" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\plataforma-ecp.application\plataforma-ecp.application.csproj" />
    <ProjectReference Include="..\plataforma-ecp.domain\plataforma-ecp.domain.csproj" />
    <ProjectReference Include="..\plataforma-ecp.infrastructure\plataforma-ecp.infrastructure.csproj" />
  </ItemGroup>

</Project>
